### ISSUE TITLE
Lwt.async failure (Failure nth)

### ISSUE THREAD

**Issue by samoht** [docker/vpnkit#131]
See https://github.com/docker/for-mac/issues/578

```
Sep 15 19:50:35 Kyutas-MacBook-Pro Docker[com.docker.slirp][3652] <Error>: Lwt.async failure (Failure nth): Raised at file "pervasives.ml", line 32, characters 22-33
    Called from file "lib/dns_forward.ml", line 38, characters 41-77
    Called from file "lib/dns_forward.ml", line 102, characters 16-57
    Called from file "src/core/lwt.ml", line 795, characters 20-24
```

**Comment by djs55** [comment]
I think the current code still has this bug at this line: https://github.com/docker/vpnkit/blob/8fbf973b7d0aa2bb2bf2096e73426d979081e5b7/src/hostnet/dns_forward.ml#L38

```ocaml
let choose_server ~nth all =
  let l = List.length all in
  let suffix = if nth > l then "(wrapped)" else "" in
  if all = []
  then None
  else Some (string_of_int nth ^ suffix, List.nth (only_ipv4 all) (nth mod l))
```
— if `only_ipv4` removes some elements from the list (IPv6 addresses) then we will call `List.nth <list shorter than l> (nth mod l)`

**Comment by yomimono** [comment]
I believe this is now fixed as the logic in [dns-forward](https://github.com/djs55/ocaml-dns-foward) is rather more sophisticated.  Closing, but please reopen if you disagree.
