### ISSUE TITLE
Include NTP server info in DHCP response

### ISSUE THREAD

**Issue by djs55** [docker/vpnkit#18]
Since we run our own DHCP server using the [charrua](https://github.com/haesbaert/charrua-core) library and can proxy NTP to the host, we should tell the VM what to do by including the host IP as the NTP server in the DHCP response. 

This involves:
- investigating whether the [charrua](https://github.com/haesbaert/charrua-core) supports this DHCP option and adding it upstream if not
- reconfiguring the DHCP server in vpnkit

**Comment by yomimono** [comment]
Fixed by #47.
