### ISSUE TITLE
Create a random mac address

### ISSUE THREAD

**Issue by justincormack** [docker/vpnkit#190]
Having all machines have `C0:FF:EE:C0:FF:EE` as their mac address is very inconvenient, eg they are indistinguishable... Can we generate a random address please...

**Comment by dsheets** [comment]
Perhaps we should allocate in the CF block <https://tools.ietf.org/html/rfc5342#section-2.3.2> to avoid collisions and confusion about OUIs?

**Comment by ijc25** [comment]
Why not just generate some random bytes, set the locally administered bit and clear the multicast bit?
